apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "daily-gateway.fullname" . }}
  labels:
    app: {{ template "daily-gateway.name" . }}
    chart: {{ template "daily-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  CORS_ORIGIN: {{ .Values.appConfig.corsOrigin }}
  MONETIZATION_URL: {{ .Values.appConfig.monetizationUrl }}
  REDIRECTOR_URL: {{ .Values.appConfig.redirectorUrl }}
  API_URL: {{ .Values.appConfig.apiUrl }}
  SCRAPER_URL: {{ .Values.appConfig.scraperUrl }}
  BESTICON_URL: {{ .Values.appConfig.besticonUrl }}
  PRIMARY_AUTH_ORIGIN: {{ .Values.appConfig.primaryAuthOrigin }}

