apiVersion: v1
kind: Secret
metadata:
  name: {{ template "daily-gateway.fullname" . }}
  labels:
    app: {{ template "daily-gateway.name" . }}
    chart: {{ template "daily-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  MYSQL_USER: {{ .Values.appConfig.mysql.user | b64enc }}
  MYSQL_PASSWORD: {{ .Values.appConfig.mysql.password | b64enc }}
  MYSQL_DATABASE: {{ .Values.appConfig.mysql.database | b64enc }}
  MYSQL_HOST: {{ .Values.appConfig.mysql.host | b64enc }}
  COOKIES_KEY: {{ .Values.appConfig.cookies.key | b64enc }}
  GITHUB_CLIENT_ID: {{ .Values.appConfig.github.client.id | b64enc }}
  GITHUB_CLIENT_SECRET: {{ .Values.appConfig.github.client.secret | b64enc }}
  GOOGLE_CLIENT_ID: {{ .Values.appConfig.google.client.id | b64enc }}
  GOOGLE_CLIENT_SECRET: {{ .Values.appConfig.google.client.secret | b64enc }}
  JWT_SECRET: {{ .Values.appConfig.jwt.secret | b64enc }}
  JWT_AUDIENCE: {{ .Values.appConfig.jwt.audience | b64enc }}
  JWT_ISSUER: {{ .Values.appConfig.jwt.issuer | b64enc }}
  SLACK_WEBHOOK: {{ .Values.appConfig.slackWebhook | b64enc }}
  ACCESS_SECRET: {{ .Values.appConfig.accessSecret | b64enc }}
  API_SECRET: {{ .Values.appConfig.apiSecret | b64enc }}
  SENDGRID_API_KEY: {{ .Values.appConfig.sendgridApiKey | b64enc }}
  BLUESNAP_API_KEY: {{ .Values.appConfig.bluesnap.apiKey | b64enc }}
  BLUESNAP_API_URL: {{ .Values.appConfig.bluesnap.apiUrl | b64enc }}
  BLUESNAP_CHECKOUT_URL: {{ .Values.appConfig.bluesnap.checkoutUrl | b64enc }}
  BLUESNAP_STORE_ID: {{ .Values.appConfig.bluesnap.storeId | b64enc }}
