version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0
  pulumi: pulumi/pulumi@2.0.0
jobs:
  build:
    docker:
      - image: circleci/node:14.13.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build
          command: yarn build
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - build
  test:
    docker:
      - image: circleci/node:14.13.0
      - image: mysql:5.7
        environment:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: 12345
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Wait for MySQL
          command: |
            for i in `seq 1 10`;
            do
            nc -z localhost 3306 && echo Success && exit 0
            echo -n .
            sleep 1
            done
            echo Failed waiting for Postgress && exit 1
      - run:
          name: Test
          command: yarn test --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ./test-results/mocha/results.xml
            MYSQL_HOST: localhost
            MYSQL_USER: root
            MYSQL_PASSWORD: 12345
            MYSQL_DATABASE: test
            NODE_ENV: test
            JWT_SECRET: 1234567890
            JWT_AUDIENCE: Daily Testing
            JWT_ISSUER: Daily API Testing
            COOKIES_KEY: topsecret
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./test-results
  build_and_push_docker:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - gcp-gcr/build-image:
          image: $CIRCLE_PROJECT_REPONAME
          tag: $CIRCLE_SHA1
      - gcp-gcr/gcr-auth
      - gcp-gcr/push-image:
          image: $CIRCLE_PROJECT_REPONAME
          tag: $CIRCLE_SHA1
  pulumi_preview:
    docker:
      - image: circleci/node:14.13.0
    steps:
      - checkout
      - pulumi/login
      - run:
          name: Install dependencies
          command: npm i
          working_directory: infra
      - run:
          name: Pulumi preview
          command: pulumi preview --suppress-outputs --stack prod -c tag=$CIRCLE_SHA1
          working_directory: infra
  pulumi_up:
    docker:
      - image: circleci/node:14.13.0
    steps:
      - checkout
      - pulumi/login
      - run:
          name: Install dependencies
          command: npm i
          working_directory: infra
      - run:
          name: Pulumi refresh
          command: pulumi refresh -y --suppress-outputs --stack prod
          working_directory: infra
      - run:
          name: Pulumi up
          command: pulumi up -y --suppress-outputs --stack prod -c tag=$CIRCLE_SHA1
          working_directory: infra
workflows:
  build:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: master
      - build_and_push_docker:
          requires:
            - build
          context: GCR
      - pulumi_preview:
          context: PROD
          filters:
            branches:
              ignore:
                - /pull\/[0-9]+/
                - master
      - pulumi_up:
          requires:
            - build_and_push_docker
          context: PROD
          filters:
            branches:
              only:
                - master
      - gcp-gcr/add-image-tag:
          requires:
            - build_and_push_docker
          context: GCR
          image: $CIRCLE_PROJECT_REPONAME
          source-tag: $CIRCLE_SHA1
          target-tag: latest
          filters:
            branches:
              only:
                - master
